# Generated by Django 3.2 on 2021-04-29 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)])),
                ('hints', models.IntegerField(default=8)),
                ('strikes', models.IntegerField(default=3)),
                ('game_data', models.JSONField()),
                ('turn', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('final_turn', models.IntegerField(default=-1)),
                ('players', models.ManyToManyField(to='hanabi.Player')),
            ],
        ),
    ]
