# Generated by Django 3.2.5 on 2021-08-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanabi', '0002_room_final_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
